### ISSUE TITLE
Mouse cursor does not change back to regular pointer after exiting the button or link area

### ISSUE THREAD

**Issue by guofoo** [moxin-org/moxin#178]
When the mouse arrow-pointer is hovering over buttons and links it changes into a hand-pointer.

After it leaves the clickable area, the pointer should change back to arrow. But this does not happen right away for most buttons and links. Most of them they change only after leaving the "containing panel" area.
Problem ares: Resources Links, Download buttons, Chat with Model, Resume Chat, Info, and Delete buttons, etc.

Exceptions are the Show All Files / Only Recommended Files buttons, here the pointer behaves properly. 
The Chat hide panel and new chat buttons are ok, same with Discover, Chat and My Models screen buttons.

**Comment by kevinaboos** [comment]
Echoing the same problem for Robrix too. Hover-exit actions don't seem to be triggering at all.

**Comment by jmbejar** [comment]
This is much of a problem in Makepad, as we discussed in recent meetings. I'm currently exploring some possible solutions but there is a chance that we should wait for fundamental changes from Makepad mouse/touch events handling system.

**Comment by jmbejar** [comment]
Most of the issues should now be fixed in `dev` branch, so let's test a bit and then close the issue once it is merged to `main`.

There is one situation where the cursor does not change back to the arrow after hovering a control. It happens with the Sort options (dropdown) but I confirmed it is an issue in all of the Makepad applications and examples. We should address this specific issue in the Makepad dropdown widget.
