### ISSUE TITLE
Model text and titles sometimes do not appear on the Discover page

### ISSUE THREAD

**Issue by kevinaboos** [moxin-org/moxin#204]
I have noticed this occasionally on both macOS and Windows (may also happen on Linux, I just haven't observed that personally).

<img width="1616" alt="image" src="https://github.com/user-attachments/assets/3342e4c0-5d27-4c0c-b594-d0e5c0b75272">

The specific titles that are missing are random and not consistent across builds and runs of Moxin. In the above image, note that the Model cards at the top of the screen and at the bottom are both missing.

**Comment by kevinaboos** [comment]
here's an example of this happening on Linux 
![image](https://github.com/user-attachments/assets/d155a282-8699-43e8-b385-d9b78cf585b2)

**Comment by kevinaboos** [comment]
I noticed when I scroll up and down on Linux, some of the text (but not all of it) will sometimes re-appear.

Is this perhaps related to caching of model card elements within the portal list? Just a guess.

**Comment by jmbejar** [comment]
Well, the issue cause is something we should think further at Makepad level. It is a situation where we are using the same labels identifiers in the context of two different views, but the widget lookup in one includes also the elements of the other widget because it is part of the view's descendants.
I feel this is an issue that will happen from time to time to developers because we tend to think the widget context is kind of isolated from other, but it is not the case with what you define in the DSL.

The short term solution for this issue is to remove the ambiguity by using unique identifiers.

**Comment by kevinaboos** [comment]
Oh interesting. Where else where those same DSL identifiers used?

**Comment by jmbejar** [comment]
Fixed on main now
